"""test

Revision ID: 447463025e89
Revises: fab4dcce52eb
Create Date: 2024-02-04 02:01:48.068462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447463025e89'
down_revision: Union[str, None] = 'fab4dcce52eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_name', table_name='media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_media_name', 'media', ['name'], unique=False)
    # ### end Alembic commands ###
